name: Deploy React App to S3

on:
  push:
    branches:
      - main  # Déploie seulement quand on push sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Assure-toi que la version correspond à ton projet

      - name: Install dependencies
        run: npm install
        working-directory: frontend  # Ajuste si ton projet est ailleurs

      - name: Build the React app
        run: npm run build
        working-directory: frontend

      - name: Deploy to S3
        run: aws s3 sync frontend/build/ s3://stratmind-frontend --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-2"  # Remplace par ta région AWS

      - name: Invalidate CloudFront Cache (optionnel)
        run: aws cloudfront create-invalidation --distribution-id E3JLZGBSSAD4LX --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        continue-on-error: true  # Ignore l'erreur si CloudFront n'est pas activé
